- packages and modules using oops
    - similar to packages
    - but here we are dealing 

In [2]:
from packages.module import *
obj=File
obj.add(4,5)

9

In [3]:
obj.mul(4,5)

20

In [4]:
obj.sub(4,5)

-1

In [1]:
from packages.module import *
obj1=Find
obj1.even(5)

odd


In [2]:
obj1.even(2)

even


In [6]:
from packages.module import *
obj2=Mod(1,2)
print(obj2.__mul__())
print(obj2.__add__())

2
3


In [1]:
from packages.module import *
obj3=Mod()
print(obj3.__add__(2,5))

TypeError: __init__() missing 2 required positional arguments: 'val1' and 'val2'

- Data science
    - Organising,processing and analaysing huge amount data.
    - It involves different disciplines like mathematical and statistical modelling.
    - Extracting data from source
    - Apply data visualization
    - Nearly 20 python libraries for data science
    - 

- Numpy
    - Numerical python
    - Fundamental package for scientific computing
    - Multidimensional array object
- Installation
    - pip install numpy
    - sudo apt get install python3 numpy
    - 

In [2]:
import numpy as np
np.__version__

'1.18.1'

In [3]:
np? # to  get short description about numpy

In [4]:
# creating arrray using Numpy
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [5]:
np.array([1.02,1,2,3,4,5])

array([1.02, 1.  , 2.  , 3.  , 4.  , 5.  ])

In [6]:
np.array([1.02,1,2,3,4,5],dtype='int') #  to get data according to datatype mentioned

array([1, 1, 2, 3, 4, 5])

In [8]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
x=np.arange(9).reshape(3,3) # to convert 1d array into multidimensional array
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.arange(2,20,1)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
dt=np.random.randint(1,50)
dt

36

In [18]:
dat=np.random.randint(1,50,size=(2,5))
dat

array([[47,  8,  2, 35, 42],
       [20, 25, 49, 15, 11]])

In [19]:
dat

array([[47,  8,  2, 35, 42],
       [20, 25, 49, 15, 11]])

In [20]:
dat=np.random.randint(1,50,size=(10,10))
dat

array([[19, 29, 45, 40,  1, 35, 13, 28, 36, 12],
       [30, 11, 15, 34,  1, 35, 10, 15, 26, 25],
       [20, 10,  3, 26, 36, 45, 39, 33, 17, 10],
       [14, 36, 24, 25, 34, 33, 33,  3, 36,  5],
       [19, 19, 41, 18, 16, 26, 43, 11,  4, 23],
       [30,  7, 44, 46, 43, 31, 12, 23, 20, 27],
       [ 1,  3,  3,  6, 20, 16, 13,  3, 39, 43],
       [ 1, 49,  8, 18, 12, 49, 41,  8, 13, 44],
       [49, 31,  7, 20, 35, 40, 13, 26,  3, 40],
       [46,  1, 23, 28, 29, 16, 46, 29,  2,  6]])

In [22]:
import numpy as np
dat=np.random.randint(1,50,size=(3,3))
print(dat)
print(dat.shape)
print(dat.size)
print(dat.dtype)
print(dat.itemsize)

[[31 29 34]
 [20 32 47]
 [25 33 21]]
(3, 3)
9
int32
4


In [23]:
print(dat)
dat[::-1]

[[31 29 34]
 [20 32 47]
 [25 33 21]]


array([[25, 33, 21],
       [20, 32, 47],
       [31, 29, 34]])

In [26]:
dat[:-1:]

array([[31, 29, 34],
       [20, 32, 47]])

In [28]:
# create a length 10 integer array filled with zeroes
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones((3,3),dtype='float') # () -tuple

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.full((3,3),12.10) # to get matrix with one element

array([[12.1, 12.1, 12.1],
       [12.1, 12.1, 12.1],
       [12.1, 12.1, 12.1]])

In [38]:
# evenly spaced elements in array using linspace
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
# Identity matrix
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [53]:
x=np.arange(0,9).reshape(3,3)
print(x)
y=np.arange(10,19).reshape(3,3)
print(y)
add=x+y
sub=x-y
mul=x*y
div=x/y
modd=x%y
print(add)
print(sub)
print(mul)
print(div)
print(modd)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[10 12 14]
 [16 18 20]
 [22 24 26]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]
[[0.         0.09090909 0.16666667]
 [0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
x=np.arange(0,9).reshape(3,3)
print(x)
y=np.random.randint(10,100,size=(3,3))
print(y)
add=x+y
sub=x-y
mul=x*y
div=x/y
modd=x%y
print(add)
print(sub)
print(mul)
print(div)
print(modd)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[88 74 76]
 [78 50 60]
 [60 19 84]]
[[88 75 78]
 [81 54 65]
 [66 26 92]]
[[-88 -73 -74]
 [-75 -46 -55]
 [-54 -12 -76]]
[[  0  74 152]
 [234 200 300]
 [360 133 672]]
[[0.         0.01351351 0.02631579]
 [0.03846154 0.08       0.08333333]
 [0.1        0.36842105 0.0952381 ]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [57]:
# trigonometric operations
t1=np.linspace(0,np.pi,3)
t1

array([0.        , 1.57079633, 3.14159265])

In [60]:
print("sin(t)=",np.sin(t1))
print("cos(t)=",np.cos(t1))
print("tan(t)=",np.tan(t1))

sin(t)= [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(t)= [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(t)= [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [61]:
x1=np.arange(1,10).reshape(3,3)
print(np.log(x1))
print(np.log2(x1))
print(np.log10(x1))
print(np.exp(x1))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]
 [2.80735492 3.         3.169925  ]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
