In [4]:
import numpy as np
np.__version__

'1.18.1'

In [3]:
print(dir(np),end=" ")

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [5]:
# vstack anf hstack
a=np.ones((3,3))
np.vstack((a,np.array((2,2,2)))) # to add row in the given matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [6]:
a=np.ones((3,3))
np.hstack((a,np.array((2,2,2))))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [7]:
a=np.ones((3,3))
b=np.array((2,2,2)).reshape(3,1)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2]
 [2]
 [2]]


In [8]:
np.hstack((a,b))

array([[1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])

In [5]:
name=['su','go','lu','vu']
age=[10,20,30,40]
weight=[50.1,60.2,70.3,80.4]
name

['su', 'go', 'lu', 'vu']

In [6]:
# create structure array using compound data types
data=np.zeros(4,dtype={'names':('name','age','weight'),'formats':('U10','i4','f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


- U10 -- Unicode string
- i4 -- translate to 4 byte integer
- f8 -- translate to 8 byte float

In [7]:
data['name']=name
data['age']=age
data['weight']=weight
print(data)

[('su', 10, 50.1) ('go', 20, 60.2) ('lu', 30, 70.3) ('vu', 40, 80.4)]


In [8]:
data[0]

('su', 10, 50.1)

In [9]:
data[1]

('go', 20, 60.2)

In [10]:
data[-1]

('vu', 40, 80.4)

# -------------------------------------------------------------------------------------------------------------------------

- pandas
    - One of data science package
    - Data manipulation tool,data analysing and data cleaning
    - built on numpy
    - developed by WeMckinney
- Installation
    - Windows
        - pip install pandas
    - Linux
        - sudo apt-get install python3 pandas
- key structures
    - series
        - sequence of data
            - syntax pd.Series(var,index=[])
    - data frames
        - 

In [11]:
import pandas as pd
pd.__version__

'1.0.1'

In [12]:
print(dir(pd),end=" ")

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_lib', '_libs', '_np_version_under1p14', '_np_version_under1p15', '_np_version_under1p16', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array

In [13]:
st='hello'
pd.Series(st)

0    hello
dtype: object

In [14]:
st1=input().split()
pd.Series(st1)

gosu ilvu


0    gosu
1    ilvu
dtype: object

In [15]:
il=['su','go']
pd.Series(il)

0    su
1    go
dtype: object

In [18]:
il1=['sugo',1,2,3,4]
pd.Series(il1)

0    sugo
1       1
2       2
3       3
4       4
dtype: object

In [19]:
pd.Series(il1,index=['a','b','c','d','e'])

a    sugo
b       1
c       2
d       3
e       4
dtype: object

In [24]:
import numpy as np
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
name=input("Enter string: ").split()
pd.DataFrame(name)

Enter string: su go


0
0  su
1  go

In [26]:
dt=[['su','go'],['il','vu']]
pd.DataFrame(dt)

0   1
0  su  go
1  il  vu

In [27]:
pd.DataFrame(dt,index=['one','two'])

0   1
one  su  go
two  il  vu

In [28]:
pd.DataFrame(dt,columns=['name','field'])

name field
0   su    go
1   il    vu

In [30]:
dic={'hi','hello','hru'}
print(type(dic))
pd.DataFrame(dic)

<class 'set'>


0
0     hi
1  hello
2    hru

In [41]:
dic1={'name':'govardhan','branch':'EEE','designation':'Btech'}
pd.DataFrame(dic1,index=[1])

name branch designation
1  govardhan    EEE       Btech

In [50]:
dic1={'name':'govardhan','branch':'EEE','designation':'Btech'}
dic2={'clg':'ysrec','subs':'psa','subs1':'pe'}
pd.DataFrame(dic2,dic1)

clg subs subs1
name         ysrec  psa    pe
branch       ysrec  psa    pe
designation  ysrec  psa    pe

In [56]:
pd.DataFrame([dic1,dic2],index=['1','2'])

name branch designation    clg subs subs1
1  govardhan    EEE       Btech    NaN  NaN   NaN
2        NaN    NaN         NaN  ysrec  psa    pe

In [62]:
s=pd.DataFrame([dic1,dic2],index=['1','2'],columns=['name','clg','branch','designation','subs','subs1'])
s

name    clg branch designation subs subs1
1  govardhan    NaN    EEE       Btech  NaN   NaN
2        NaN  ysrec    NaN         NaN  psa    pe

- Retrive data fromm dataframe
    - loc
        - data in that index position
    - iloc
        - Normal index value

In [63]:
s

name    clg branch designation subs subs1
1  govardhan    NaN    EEE       Btech  NaN   NaN
2        NaN  ysrec    NaN         NaN  psa    pe

In [64]:
s.loc['1']

name           govardhan
clg                  NaN
branch               EEE
designation        Btech
subs                 NaN
subs1                NaN
Name: 1, dtype: object

In [67]:
s.iloc[0] # index based

name           govardhan
clg                  NaN
branch               EEE
designation        Btech
subs                 NaN
subs1                NaN
Name: 1, dtype: object

In [68]:
# adding a colum to the existing dataframe
s['column']='value'
s

name    clg branch designation subs subs1 column
1  govardhan    NaN    EEE       Btech  NaN   NaN  value
2        NaN  ysrec    NaN         NaN  psa    pe  value

In [69]:
print(s)
s.T # transposing

        name    clg branch designation subs subs1 column
1  govardhan    NaN    EEE       Btech  NaN   NaN  value
2        NaN  ysrec    NaN         NaN  psa    pe  value


1      2
name         govardhan    NaN
clg                NaN  ysrec
branch             EEE    NaN
designation      Btech    NaN
subs               NaN    psa
subs1              NaN     pe
column           value  value

In [73]:
s.drop('clg')

KeyError: "['clg'] not found in axis"